### ISSUE TITLE
question about removing white space around pictures and implementing all time history....

### ISSUE THREAD

**Issue by peters77** [dcapslock/weewx-responsive-skin#11]
Hi,

I use your weewx Responsive skin and modified it to my needs. 
Thanks for sharing it, the skin is very nice and I'm verry happy. :-) 

Could you give me a hint howto remove the white space around all the pictures and content in a panel-body?
![Bildschirmfoto 2020-07-07 um 19 01 41](https://user-images.githubusercontent.com/8840918/86816995-c6b22080-c084-11ea-89a0-b7b0a01007b1.png)

Thanks in advance. 

I found this in the google weewx user really group https://groups.google.com/forum/#!topic/weewx-user/Dfl7_i0trGI  and it would be great if you could implement the historygenerator in your the Responsive skin too like Richard G did here https://github.com/gedger/alltimeSeasons. 

Would be great. 
My site with your adapted skin:
https://wetter.hcpeters.de/

Regards,

Christian

**Comment by dcapslock** [comment]
Hi Peter,

Glad you like the skin.

To remove the padding you need to overwrite the default bootstrap .panel-body CSS padding of 15px.

Regarding the history generator, I am not a fan of putting HTML into a Weewx generator. It should be in the template so its easily changed. So while I could implement the history generator, I don’t agree with its method. However as it stands you could include the generator php, then either add a panel to the main page below the graphs OR create a new page using the main page as a template, and replaced the graphs with the history generator tags.

If I get some time I may have a look. However at the moment I will not have time before the end of July.

Regards

Darryn Capes-Davis

**Comment by peters77** [comment]
Hi Darryn,

thank you for the hint. I'm not very skilled regading programming but with the help of google I figured out how to change the padding:

```
<style>
#mypanelId{
     padding: 2px;
}
</style>
```

and 

`<div class="panel-body" id="mypanelId">`

did the trick for me. 

Yes, maybe it's not the best solution regarding putting html in a generator. 
Maybe you will have some fun to implement it somtimes or add your own way to implement such an useful overview.
I'll try to add the php somehow to your skin...

Regards,

Christian
