### ISSUE TITLE
BOM warnings broken again

### ISSUE THREAD

**Issue by rodyager** [dcapslock/weewx-responsive-skin#13]
The BOM now doesn't like the new user-agent.

**Comment by dcapslock** [comment]
Its not just the user agent. Remote fetch needs to be more like browser as well, including using Keep-alive. As urllib2 does not support keep-alive the request needs to use httplib. FTP is still using urllib2. Fix has been applied in latest aussearch.py. NOTE: Have not tested in weewx4/python3 but should work as long as I have the import right for http.client, which is what httplib is called in python3.

**Comment by dcapslock** [comment]
Confirmed with Python3 user all is good so closing issue.
