### ISSUE TITLE
 [Errno ftp error] 200 Switching to Binary mode.

### ISSUE THREAD

**Issue by glennmckechnie** [dcapslock/weewx-responsive-skin#7]
This isn't an error with aussearch.py, but an error with urllib.py that I'm getting with the system here.
Debian stretch 9.0 (stable)  Although I have a niggling suspicion that it started occuring before that upgrade?
Interesting that there is no mention from anyone else, so I assume you're all error free. And, that always makes me doubt my sanity. :-)

I'm putting this here as an advance alert in case I'm not, and it does bite someone else.

On aussearch.py attempting to download a non-stale version of the BOM files, I'll get the first file downloaded then nothing else except the following error message in the logs.

    aussearch: cannot download xml file ftp://ftp.bom.gov.au/anon/gen/fwo/IDV10753.xml: [Errno ftp error] 200 Switching to Binary mode.
    aussearch: cannot download xml file ftp://ftp.bom.gov.au/anon/gen/fwo/IDV17102.xml: [Errno ftp error] 200 Switching to Binary mode.
    aussearch: cannot download xml file ftp://ftp.bom.gov.au/anon/gen/fwo/IDV10705.xml: [Errno ftp error] 200 Switching to Binary mode.

 and then approx 700 odd lines of feedback when the file is found to be missing, stale, whatever and aussearch plows on regardless before giving up in disgust.
[...]
    Jul 19 06:54:04 xxx [15683]: ****    File "/usr/share/weewx/user/aussearch.py", line 365, in __getattr__
    Jul 19 06:54:04 xxx [15683]: ****      if self.root_node is not None:
[...]

Doing a bit of searching on it turns up a couple of fixes - see https://bugs.python.org/issue27973 for the full story.
The fix I've used is at the end of that thread and involves reverting the changes to urllib.py as outlined at https://hg.python.org/cpython/rev/44d02a5d59fb  What was taken away, must be readded.

A copy of that change follows

 
    --- a/Lib/urllib.py
    +++ b/Lib/urllib.py
    @@ -932,13 +932,7 @@ class ftpwrapper:
             return (ftpobj, retrlen)
         def endtransfer(self):
 
    -        if not self.busy:
    -            return
 
             self.busy = 0
 
    -        try:
    -            self.ftp.voidresp()
    -        except ftperrors():
    -            pass
 
         def close(self):
             self.keepalive = False

Another fix that I tried on a whim, was to make a change to aussearch.py Usually whimsical changes have no affect, this one worked flawlessly. No hiccups.

    --- aussearch.py        2017-07-20 16:24:45.150449791 +1000
    +++ aussearch2.py       2017-07-20 16:44:06.084163158 +1000
    @@ -10,7 +10,7 @@
     import json
     import os
 
    -from urllib import urlopen
    +from urllib2 import urlopen
 
     import weewx.units
     import weeutil.weeutil

Thoughts?

**Comment by dcapslock** [comment]
Commit https://github.com/dcapslock/weewx-responsive-skin/commit/5c147e50e098b796cb8589f5c6678852585274c5 is a work around for the issue.
